"""add usuarios table and usuario_id to tarefas

Revision ID: 62f92d43a5bd
Revises: 19d8e53e9e7a
Create Date: 2026-01-11 15:54:01.792437

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62f92d43a5bd'
down_revision: Union[str, Sequence[str], None] = '19d8e53e9e7a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=250), nullable=False),
    sa.Column('senha', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.add_column('tarefas', sa.Column('id_usuario', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'tarefas', 'usuarios', ['id_usuario'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tarefas', type_='foreignkey')
    op.drop_column('tarefas', 'id_usuario')
    op.drop_table('usuarios')
    # ### end Alembic commands ###
